### ISSUE TITLE
AV1720: Include local functions

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#108]
### Existing rule:
**`Name methods using a verb or a verb-object pair (AV1720)`**
`Name methods using a verb like Show or a verb-object pair such as ShowDialog. A good name should give a hint on the what of a member, and if possible, the why.`
`Also, don't include And in the name of a method. It implies that the method is doing more than one thing, which violates the single responsibility principle explained in AV1115.`

### New language features to consider:
* local functions
I think this rule applies to local functions as well.

Proposal:
* Replace "methods" with "methods and/or local functions" (in title and text)
* Convert the text-reference to AV1115 into a hyperlink

**Comment by dennisdoomen** [comment]
:+1:

**Comment by bkoelman** [comment]
I thought that we already had cross-reference links between rules. But it appears we do not. Filed #116 to make that possible.
