### ISSUE TITLE
AV2402: Update for ordering of using static and aliases

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#110]
### Existing rule:
**`Order and group namespaces according to the company (AV2402)`**
`Microsoft namespaces are first. Then any other namespaces in alphabetic order.`

### New language features to consider:
* using static
This enables to import a class name into scope.
* namespace aliasing (not new, but missing)

Resharper default settings move regular namespace imports to the top, but leaves `using static` and `using aliases` unaffected. Example:
```csharp
using System;
using System.Threading.Tasks;
using Custom;
using SystemConsole = System.Console;
using static Custom.Z;
using CustomX = Custom.X;
using static System.Math;

namespace ConsoleAppNewLang
{
    internal class Program
    {
        public static async Task<int> Main(string[] args)
        {
            var max = Max(1, 2);
            SystemConsole.WriteLine(max);
            return await GetAsync(new CustomX());
        }

        private static Task<int> GetAsync(CustomX x)
        {
            var y = new Y();
            var s = S;
            throw new NotImplementedException();
        }
    }
}

namespace Custom
{
    public class X
    {
    }

    public class Y
    {
    }

    public static class Z
    {
        public static string S;
    }
}
```

This does not help much to come up with a scheme.

Proposal: (with alphabetic ordering inside each group):
* System namespace imports
* Other namespace imports
* Static namespace imports (system first)
* Namespace alias declarations (system first)

This would require the next order for the example above:
```csharp
using System;
using System.Threading.Tasks;
using Custom;
using static System.Math;
using static Custom.Z;
using SystemConsole = System.Console;
using CustomX = Custom.X;
```

**Comment by dennisdoomen** [comment]
I prefer a clear separation between system namespaces and custom namespaces (with an empty line in between for readability). However, I am in doubt where namespace aliases and static namespaces should be separated as well, or just part of the previous two groups. During code review, most people ignore namespace changes, but I find them useful. They give hints on incorrect usage of dependencies. Static namespaces are the equivalent of normal namespaces. And aliases are important to resolve naming conflicts.

**Comment by bkoelman** [comment]
So there does not seem to be any good reasons for a particular ordering, concerning static imports and namespace aliases.

That leaves us these options:
1. Just pick some arbitrary ordering, if we believe a *consistent* order throughout a codebase is important.
2. Leave the existing rule as-is and let each individual put them anywhere they like.
3. Follow R# and mention they should come after regular namespace imports. Do not recommend any total ordering like I proposed initially.

**Comment by dennisdoomen** [comment]
I vote for 3.
