### ISSUE TITLE
Add support for cross-reference links between rules

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#116]
Before we can start adding relative links between rules (for example: `..\1000_ClassDesignGuidelines.md#av1004`), I expect some work in the build process is needed to not break PDF rendering.

**Comment by dennisdoomen** [comment]
This should have become much easier now with the new site.

**Comment by dennisdoomen** [comment]
This is something I'd like to fix as soon as possible.

**Comment by dennisdoomen** [comment]
Rules are now clickable on the site, in the generated HTML and even in the PDF.
