### ISSUE TITLE
Rule: Using directives inside/outside namespace declarations

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#120]
Should using directives be defined outside or inside namespace declarations?

```csharp
// outside
using System;
using System.Collections.Generic;

namespace Company.Product.Subsystem
{
    public class Customer
    {
        // ...
    }
}
```

```csharp
namespace Company.Product.Subsystem
{
    // inside
    using System;
    using System.Collections.Generic;

    public class Customer
    {
        // ...
    }
}
```

And why should we have a rule for that?

From https://stackoverflow.com/questions/125319/should-using-statements-be-inside-or-outside-the-namespace#16092975:
> It is always dangerous to move the usings from one location to another because the search hierarchy changes, and another type may be found. Therefore, choose one convention and stick to it, so that you won't have to ever move usings.

**Comment by bkoelman** [comment]
Personally I would vote for defining them outside. Because Visual Studio does that by default. And I suspect that it's more commonly used. 

But ultimately it is just a matter of taste.

**Comment by dennisdoomen** [comment]
I agree.
