### ISSUE TITLE
Reflect support for latest language features in title

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#124]
As support is being added for newest C# versions, the current title no longer covers its content:

*A set of coding guidelines for **C# 3.0, C# 4.0 and C# 5.0**, design principles and layout rules for improving the overall quality of your code development.*

Several options come to mind:
1. Keep as-is
    As it is no longer accurate, I don't think this makes sense.
2. Change to: C# 1.0 - C# 7.1
    Version 1.0 because many guidelines concern OO principles in general, which are applicable to all versions of the language.
3. Change to: C#
    Not mentioning versions makes the document usable for eternity. But the downside is that people may consider it old and outdated as well. I think being specific would help new visitor to quickly classify scope.

**Comment by dennisdoomen** [comment]
Yeah, the title is what makes the repo discoverable. I propose to rename it to *C# 5.0, C# 6.0 and C# 7.0*. 

After the updates are more or less done, I also want to create explicit releases for every change.

**Comment by bkoelman** [comment]
Why the last **three** major versions only? And why not include 7.1?

**Comment by dennisdoomen** [comment]
For marketing purposes....

**Comment by dennisdoomen** [comment]
This can be closed now, right?

**Comment by bkoelman** [comment]
I don't mean to be disrespectful, but I'm not so happy about this name for several reasons:
1. It's ignoring that the compiler team has switched to point releases. C# 7.1 is out, 7.2 ships with VS 2017 Update 5 (currently in Preview3). 7.3 and 8.0 are being designed/developed at the moment.  This is not going away, better adopt the new scheme.
2. 'For marketing purposes' I do not get. To me it sounds similar to 'for political reasons' which are different words for 'I have no reasonable explanation / don't wanna say'.
3. The target audience for this repo I would say are experienced C# developers. While juniors are often busy with actually putting something together that works, more experienced folks see the long-term effects of quick-and-dirty solutions and are looking out for guidance like here. I would not want to mis-inform those potential expereienced users by a title that does not cover what this is about. 
4. Giving the repro a name that does not cover its contents is not something people expect from open-source. I believe it should be open and honest, simply put things as they are without sugar on it.
5. I've wanted to make a list of all rules along with which versions of C# they cover to make insightful what the repo really covers mostly. But my time is limited at the moment unfortunately.

**Comment by dennisdoomen** [comment]
> I don't mean to be disrespectful

Not at all. If you can't share your opinions here anymore, what's the point of doing OSS ;-)

> `For marketing purposes` 

It means that I want the guidelines to be discoverable through the search engines. So with that in mind, I propose to list all supported versions, including point releases. 

Would that work for you?

**Comment by bkoelman** [comment]
Yes that would work for me. Thanks.
