### ISSUE TITLE
Release page does not allow downloading

### ISSUE THREAD

**Issue by Kelson448** [dennisdoomen/CSharpGuidelines#132]
On the main page of the project, under the "Where do I get them?" header, there is a link to the release page.  On the linked page, the pdf and html download links for both the cheat sheet and guidelines lead to https://archive.codeplex.com/?p=csharpguidelines , which only has a link leading back to the main page of the project on github and an archive download (for an older version?). In the very least it is a somewhat confusing loop.

**Comment by 9swampy** [comment]
FWIW haven't been able to find (yet) where the pdf is now but if it helps http://csharpcodingguidelines.com/ has at least the html.

**Comment by MarcMenghin** [comment]
I'm also looking for the PDF and ReSharper files. Can't they be added to Github? Onto the releases section instead of links to codeplex?

**Comment by MarcMenghin** [comment]
extracted files from codeplex archive: [CSharpGuidelines_v5.0.0.zip](https://github.com/dennisdoomen/CSharpGuidelines/files/1829753/CSharpGuidelines_v5.0.0.zip)

looks like the correct ones for me.

**Comment by Kelson448** [comment]
Actually, those appear to be an older version (they state for c# 3.0, 4.0 and 5.0). The link  @9swampy posted says "for C# 5.0, 6.0 and 7.0", but has the same date October 18, 2016 as the archive. Was there a more updated version? or are those dates just not updated? There does appear to be commits well past that date.

**Comment by Kelson448** [comment]
Thanks for finding it either way, one of the projects I am working on is version 4 currently, so I did need that version of the files specifically.
