### ISSUE TITLE
Suggestion: static classes cause pain when they have dependencies

### ISSUE THREAD

**Issue by MCCoolMoDAue** [dennisdoomen/CSharpGuidelines#135]
we recently started developing using a design method, which can lead to a ton of static functions and classes.
This all sounds good and well until you have dependencies.
We now have static classes that depend on other non-static classes.
Imagining setting up your application using something like autofac is weird to say the least.

For me this speaks against static classes.
Maybe this would be a nice reason / indication why not to use static classes.

The reason of testability is in the document already and is connected to what i suggested, but this might clear things up a bit.

**Comment by MCCoolMoDAue** [comment]
good point!
in our case we don't have a mutable state, but we have a dependency that we
get from a service locator (I know, bad idea, but that's what we have).
In my opinion service locator, singleton or just static members are all
very similar.
So our static class depends on something else that is static.
Having a static mutable state would be just as bad, but slightly different.

long story short:
static classes can lead to static dependencies (of some sort, service
locator, other static classes, singletons...)
also like you said, best avoid static mutable state.

My concrete problem is that you cannot use polymorphism with static classes.
Because of that we have a ton of if statements deciding which behavior our
(static) dependency should have...
I'm rambling...

2018-04-11 9:21 GMT+02:00 Dennis Doomen <notifications@github.com>:

**Comment by bkoelman** [comment]
Related rules: 
- [AV1008: Avoid static classes](https://github.com/dennisdoomen/CSharpGuidelines/blob/61b5f136edbbaa0d625d80a4a11158e101a0af65/_pages/1000_ClassDesignGuidelines.md#-avoid-static-classes-av1008-)
- [AV1125: Don't expose stateful objects through static members](https://github.com/dennisdoomen/CSharpGuidelines/blob/c28253cb9ffacd5f42cd8d50acf117c697679c1c/_pages/1100_MemberDesignGuidelines.md#-dont-expose-stateful-objects-through-static-members-av1125-)

I'd be happy to help this issue forward. Is there any concrete work that needs to be done to get this closed?

**Comment by dennisdoomen** [comment]
Closing as there was no response for over a year now.
