### ISSUE TITLE
Prefer language syntax over explicit calls to underlying implementations

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#138]
How about this for a new rule?
AV1526 or AV2201: Prefer language syntax over explicit calls to underlying implementations

---
Prefer:
```
	(string, int) tuple = ("", 1);
```
rather than:
```
	ValueTuple<string, int> tuple = new ValueTuple<string, int>("", 1);
```
---
Prefer:
```
	DateTime? startDate;
```
rather than:
```
	Nullable<DateTime> startDate;
```
---
Prefer:
```
	if (startDate != null) ...
```
rather than:
```
	if (startDate.HasValue) ...
```
---
Prefer:
```
	if (startDate > DateTime.Now) ...
```
rather than:
```
	if (startDate.HasValue && startDate.Value > DateTime.Now) ...
```

**Comment by dennisdoomen** [comment]
Sure. I think the Framework Guidelines are the best fit.

Would be nice if we can also remove one...

**Comment by dennisdoomen** [comment]
> How about merging these with AV2201?

That one is only about type aliases, so it needs something else.



> If I had to pick one to remove, it would be AV2215.

Agreed



> Another candidate to remove could be AV2205:

Agreed
