### ISSUE TITLE
AV1739 Underscore for unused lambda parameters

### ISSUE THREAD

**Issue by ygoe** [dennisdoomen/CSharpGuidelines#15]
That doesn't quite scale. See, in the example code you need one underscore for the first parameter and already two of them for the second (because they must be unique and there is only one underscore).

Instead, I now take lambda expressions as the one and only place where I allow single-letter variable names. (Aside of maybe very short loops. Really short.) It doesn't hurt to have unused single-letter parameters here. The example code would look like this:

    button.Click += (s, e) => HandleClick();

s and e are for the common sender and e. Which is wrong again because e is actually not allowed here. I mostly rename the generated 'e' parameter to args. So the two parameters should actually be called s and a. But then again, it's not very important because they're unused anyway...

**Comment by dennisdoomen** [comment]
Thanks for your explanation. I must say I prefer the underscore, but I would actually never use it as in the example. I'll fix the example. 

BTW, I do accept Pull Requests :smirk:

**Comment by dennisdoomen** [comment]
Concluded that I prefer the way it is written now
