### ISSUE TITLE
AV1570 Check as for null

### ISSUE THREAD

**Issue by dg9ngf** [dennisdoomen/csharpguidelines#17]
An addition to this:

Using the 'as' is more performant when you expect that the object may be of another type. But then you must also expect the null result. If you don't expect another type, always cast with parentheses. If it *is* another type, a meaningful InvalidCastException will be thrown. (Which, together with try/catch, on the other side is slower than the 'as' operator.)

**Comment by dennisdoomen** [comment]
Agreed.
