### ISSUE TITLE
Get rid of CodePlex and redirect csharpcodingguidelines.com here

### ISSUE THREAD

**Issue by ygoe** [dennisdoomen/CSharpGuidelines#18]
It's confusing to have two different code hosting sites in active use for a single project. Intro, additional links and releases are on CodePlex while the current source and issues are on GitHub. Why not pull everything together on GitHub?

I believe GitHub didn't support uploading compiled files roughly around the time of your last release. They did further back in the past, and they do again for a while. You can tag your releases in Git and attach additional files to them in the Releases section.

The readme.md file in this repository could easily hold all the info from the CodePlex start page.

Plus GitHub is more reliable and quicker than CodePlex. In fact anything is better than a Microsoft website.

**Comment by dennisdoomen** [comment]
To be honest, the only reason why I'm still on CodePlex, because it pays for my expenses....

**Comment by dennisdoomen** [comment]
Resolved using https://csharpcodingguidelines.com/
