### ISSUE TITLE
Broken external links under Useful Links

### ISSUE THREAD

**Issue by jcbaezk** [dennisdoomen/CSharpGuidelines#185]
There are links to external resources under Useful Links that don't work anymore.

- Jeremy D. Miller’s Blog (http://codebetter.com/blogs/jeremy.miller/)

- LINQ Framework Design Guidelines (https://blogs.msdn.microsoft.com/mirceat/2008/03/12/linq-framework-design-guidelines/)

- Best Practices for c# async/await (http://code.jonwagner.com/2012/09/06/best-practices-for-c-asyncawait/)

Also the link under AV1125 does not work.

- Isolate the Ugly Stuff (http://codebetter.com/jeremymiller/2005/10/21/haacked-on-tdd-and-jeremys-first-rule-of-tdd/)

**Comment by dennisdoomen** [comment]
Thanks for reporting these!

**Comment by dennisdoomen** [comment]
Fixed.
