### ISSUE TITLE
AV1720 Name methods using verb-object pair

### ISSUE THREAD

**Issue by dg9ngf** [dennisdoomen/csharpguidelines#19]
Or just a verb. In OOP, methods are often operations on the instance. They are actions that the object can perform. Tell a socket to `Close`, or a file to `Delete` itself, or a collection to `Clear`. (See also AV1710: Don't repeat the name of a class (...) in its members) Of course the 'object' part (as in verb-object) is helpful if it's not clear from the context what thing a method will work on.

I know that PowerShell cmdlets suggest a Verb-Object naming but there's often no instance that the command applies to.

**Comment by dennisdoomen** [comment]
Agreed. Will update that.
