### ISSUE TITLE
Suggestion: Per-Rule metadata

### ISSUE THREAD

**Issue by julianbartel** [dennisdoomen/CSharpGuidelines#195]
Proposal is to have additional metadata on a per rule basis. This could be achieved by moving every rule into its own markdown file so it has its own front matter. 
Use case examples:
 - references to static code analysis tools covering the rule
 - additional rules for other languages (eg. C++), where the majority of rules ist shared across languages - with the language specified in the rule, a developer can filter for rules applying to his language.
 - the same as above but for team specific rules.

The problem I see is that this would be an absolutely breaking change. However, 
I have a working prototype and could provide a PR if you are interested.

**Comment by dennisdoomen** [comment]
I'm actually quite interested in that. I've been considering the same thing. It would also make everything more searchable (potentially).

**Comment by julianbartel** [comment]
Created PR #196 but marked as draft as I would like to discuss a few points (provided in PR comment).

**Comment by julianbartel** [comment]
Now that this has been done, the issue can be closed.
@dennisdoomen Thanks for your support and accepting PR #196.

**Comment by dennisdoomen** [comment]
Thank you for this awesome contribution. It made the site so much better.
