### ISSUE TITLE
AV1551 Call the most overloaded method from other overloads

### ISSUE THREAD

**Issue by dg9ngf** [dennisdoomen/csharpguidelines#20]
Do you have any explanation for this one?

This likely leads to duplicate code. You set the same default value in multiple overloads. Change one, forget the others (even though they're close to each other), and you have a problem. Your sample code would happily work if each overload only adds the next parameter and lets the other overloads add all other parameters. This way, you only add one parameter per overload and only have each value in a single place.

Obviously, if leaving out multiple parameters requires to set a number of different values, calling a longer overload is necessary. But that comes from a functional requirement.

I'd make the phrase about the **order of parameters** in all overloads the main point and leave out the rest.

**Comment by dennisdoomen** [comment]
What would the example of [AV1551](https://github.com/dennisdoomen/csharpguidelines/blob/master/Guidelines/1500_MaintainabilityGuidelines.md#call-the-most-overloaded-method-from-other-overloads-av1551-) look like?

**Comment by dg9ngf** [comment]
I'd change the code to this:

    public class MyString  
    {
        // ...
        public int IndexOf(string phrase)  
        {  
            return IndexOf(phrase, 0);   // <-- not calling 3-param but 2-param
        }

        public int IndexOf(string phrase, int startIndex)  
        {  
            return IndexOf(phrase, startIndex, someText.Length - startIndex);   // no change
        }

        public virtual int IndexOf(string phrase, int startIndex, int count)  
        {  
            return someText.IndexOf(phrase, startIndex, count);   // no change (actual implementation)
        }  
    }
