### ISSUE TITLE
Proposal for new rule: Write code that is easy to debug

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#206]
I sometimes see developers write lines like this:

```csharp
string result = ConvertToXml(ApplyTransforms(ExecuteQuery(GetConfigurationSettings(source))));
```

in an attempt to keep the number of statements within a method below the required threshold. I would prefer the code to read like this instead (using `var` for brevity):

```csharp
var configurationSettings = GetConfigurationSettings(source);
var queryResult = ExecuteQuery(configurationSettings);
var transformed = ApplyTransforms(queryResult);
var xml = ConvertToXml(transformed);
```

Because now it becomes possible to add breakpoints to the individual steps and inspect their outcomes without the need to step into them.

Thoughts?

**Comment by bkoelman** [comment]
Note this is not about chaining method calls, which is a common pattern in fluent APIs.

**Comment by dennisdoomen** [comment]
Yeah, I think there's a balance to uphold to. 

Something I like about Rider is that when you press F11 (step into), it allows you to choose the method in that nested call you want to dive into. It's call [Smart Steps](https://blog.jetbrains.com/dotnet/2020/04/30/smart-step-enabled-default-debugger-updates-rider-2020-1/).

**Comment by bkoelman** [comment]
Wow, that's an awesome Rider feature! Nice, I did not know about that.

Do you still think this rule should be added?

**Comment by dennisdoomen** [comment]
Yes, it makes sense. But again, we want to make sure there's a balance. Just putting everything on a separate line is a bit too much for me.

**Comment by bkoelman** [comment]
Sounds good to me. How would you phrase the rule then?

**Comment by dennisdoomen** [comment]
I'm in doubt between "Avoid overuse of nested calls", which is very specific, and your original title.

**Comment by bkoelman** [comment]
We can have both. The goal is easy to debug (title) and the way to achieve that is by not overusing nested calls (in the text).

**Comment by dennisdoomen** [comment]
Let's do that.

**Comment by bkoelman** [comment]
I've submitted a PR earlier, but now I started thinking some more about this. While Smart Steps prevents us from needing to step-into/step-out multiple times, it doesn't help in showing intermediate return values. How I would do that:
1. Step into the method
2. Scroll to the closing curly of the method body and select Run to here
3. Inspect the magical $ReturnValue in watch/locals/auto window

Alternatively I may paste the method call in Intermediate window and see the outcome there. Assuming the method has no side effects, which I need to verify first.

Is there an easier way I'm unaware of? Can you provide an example where nested method calls (not properties) would be a good thing? I can't think of any.

**Comment by dennisdoomen** [comment]
Given this piece of code:

![image](https://user-images.githubusercontent.com/572734/81526740-caf9e000-9358-11ea-8ea3-a648897f0093.png)

As soon as I complete that nested call, this is what Rider shows me:

![image](https://user-images.githubusercontent.com/572734/81526764-db11bf80-9358-11ea-87c6-dda65a7072fc.png)

**Comment by bkoelman** [comment]
Looks like I missed something indeed! :)

**Comment by dennisdoomen** [comment]
But do you still stand behind your rule?

**Comment by bkoelman** [comment]
I think the rule as currently formulated is still valid (do not overuse). Now I understand why "not overuse" is more appropriate than saying each call result must be put into a separate variable, which I believed to be best earlier.
