### ISSUE TITLE
Proposal: relax parenthesis usage (AV2400)

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#207]
Existing guidance:

*Add parentheses around every binary expression, but don’t add parentheses around unary expressions. For example if (!string.IsNullOrEmpty(str) && (str != "new"))*

Most developers are unaware that && has higher precedence than ||, which makes expressions like below hard to read:

```csharp
if (a && b || c)
{
}
```

For other cases I think precedence is obvious for most developers:
```csharp
if (a > b && c < d)
{
}

int result = a + b * c;
```

Recently the usage of parentheses was added to Visual Studio / .editorconfig:
```ini
# Parentheses preferences
dotnet_style_parentheses_in_arithmetic_binary_operators = always_for_clarity:silent
dotnet_style_parentheses_in_other_binary_operators = always_for_clarity:silent
dotnet_style_parentheses_in_other_operators = never_if_unnecessary:silent
dotnet_style_parentheses_in_relational_binary_operators = always_for_clarity:silent
```
and to Resharper:
![image](https://user-images.githubusercontent.com/10324372/81344311-d5954a80-90b6-11ea-8543-a7bcc753e08b.png)

This enables us to be more specific on which cases parentheses are helpful and have automated formatting settings for them.

**Comment by dennisdoomen** [comment]
So how would you change the rule?

**Comment by bkoelman** [comment]
Remove redundant parentheses in expressions if they do not clarify precedence. Add parentheses in expressions to avoid non-obvious precedence. For example, in nested conditional expressions: `overruled || (enabled && active)`, bitwise and shift operations: `foo | (bar >> size)`.

**Comment by dennisdoomen** [comment]
I think that's a good balance.
