### ISSUE TITLE
Bug: quoted formatting is not applied in titles on csharpcodingguidelines.com

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#209]
![image](https://user-images.githubusercontent.com/10324372/81508872-0f5c9000-9307-11ea-8978-cab75fbb409f.png)

**Comment by dennisdoomen** [comment]
That's weird. Nothing has been changed on the underlying infrastructure.

**Comment by bkoelman** [comment]
This and https://github.com/dennisdoomen/CSharpGuidelines/pull/230#issuecomment-1028267678 could be caused by:

https://github.com/dennisdoomen/CSharpGuidelines/blob/4ad2ebe71296a1d6e70d2f22f7b997edcd9e257d/Build/default.ps1#L108


Because the title gets wrapped in an HTML tag, I _suspect_ this results in upstream tooling to skip formatting. However I know very little of the tooling used to generate the website, so I may be wrong entirely.
