### ISSUE TITLE
Formatting issue for code samples on csharpcodingguidelines.com

### ISSUE THREAD

**Issue by jcbaezk** [dennisdoomen/CSharpGuidelines#211]
[Naming Conventions (AV1700)](https://csharpcodingguidelines.com/naming-guidelines/)
![image](https://user-images.githubusercontent.com/48487197/85514510-06dcc200-b5f4-11ea-8935-3cdd173fd3b1.png)

[Layout Guidelines (AV2400)](https://csharpcodingguidelines.com/layout-guidelines/)
![image](https://user-images.githubusercontent.com/48487197/85514662-2ecc2580-b5f4-11ea-9824-783fb9deb91a.png)

**Comment by julianbartel** [comment]
👍
I wanted to fix this since long time but always postponed... PR will come soon ;-)
