### ISSUE TITLE
ndepend rules for CSharpGuidelines

### ISSUE THREAD

**Issue by janschreier** [dennisdoomen/CSharpGuidelines#217]
Hi Dennis,
thanks for putting up your rules here! We'll take those as starting point to get going with our own coding guidelines (finally!). 
Before I re-invent the wheel, I thought I'd ask, if you have, by any chance, created ndepend rules for these guidelines that you might be willing to share.

looking forward to an answer and best regards,
Jan

**Comment by dennisdoomen** [comment]
Hi Jan. Thank you for those kind rules. Unfortunately no, I'm not using NDepend anymore.

**Comment by janschreier** [comment]
thanks for your answer Dennis.
I'll put up a repo on my account, once I've done this task (in case somebody find's the issue in the future)
