### ISSUE TITLE
Async guidance

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#231]
In response to #230, I'd like to point out https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md, which you may want to take parts from or just link to it.

**Comment by bkoelman** [comment]
Perhaps add this to https://github.com/dennisdoomen/CSharpGuidelines/blob/master/_pages/9999_ResourcesAndLinks.md? @dennisdoomen what do you think?

**Comment by dennisdoomen** [comment]
Yeah, I would be totally okay about that.
