### ISSUE TITLE
Publish content using GitHub pages

### ISSUE THREAD

**Issue by kevinkuszyk** [dennisdoomen/CSharpGuidelines#24]
It would then be searchable in Google etc, you could `CNAME` csharpcodingguidelines.com to it (with Ads if need be), and then close down the codeplex site (#18).

I'm not sure how it would work if you still want to build the PDF file.

Thoughts?

**Comment by dennisdoomen** [comment]
Yeah, but I suck at web design.

**Comment by kevinkuszyk** [comment]
Me too, but the default theme is ok, and there are some good free Jekyll themes.  Who knows, someone in the community might even do some design work for it!

If you can live with dropping the PDF and will take a PR, I'll spend some time refactoring it.

**Comment by dennisdoomen** [comment]
What would that PR do?

**Comment by kevinkuszyk** [comment]
I was thinking about a markdown page for each section, a home page, and renaming them to make the urls seo friendly.

It's a bit of a moot point now thorough as I hadn't realised the urls for repros take the form `http://username.github.io/repository`.

I'm happy for you to close as I think it's a non-starter for now.

**Comment by dennisdoomen** [comment]
Why not? If you can get the Jekyll stuff to work, it should be more easy to support that.

**Comment by kevinkuszyk** [comment]
So, the GitGub pages url is `http://dennisdoomen.github.io/csharpguidelines`, if you make `csharpcodingguidelines.com` a `CNAME` for `dennisdoomen.github.io` you'd end up with `http://csharpcodingguidelines.com/csharpguidelines`.  

In my view it would be better to host it without the `/csharpguidelines` on the end.

If you like the idea of turning this into a website, I'm happy to spend some time wiring up Jekyll.  I don't think it should be too difficult to make a CI build using AppVeyor to generate the HTML and publish it to an Azure website - that way it can be hosted at http://www.csharpcodingguidelines.com.

I can't make any commitment on *when* I'll be able to do this though - I have a lot of client work on at the moment.

**Comment by dennisdoomen** [comment]
Sounds awesome. Although I would prefer to host it on the `github.io` domain since that's free. We're  not in a hurry, so I would give you infinite credits if you can pull this off. I have too many open-source projects next to my day job to pull this off on a short term.

**Comment by dennisdoomen** [comment]
Is this still a thing that we want to happen?

**Comment by dennisdoomen** [comment]
Would Gitbook be an option?

**Comment by kevinkuszyk** [comment]
> Is this still a thing that we want to happen?

I still think it's a good idea.

> Would Gitbook be an option?

I wan't aware of them until I saw your post.  I just has a quick look - looks like a good product.

Also, apologies - I don't have a lot of free time at the moment, so if anyone else wants to pick this up, feel free to do so.

**Comment by Mackiovello** [comment]
I'm maintaining a couple of GitBook projects. These projects often only contain markdown files, this repo is a little different. I'll give it a shot because it would be handy to make these guidelines more available.

**Comment by dennisdoomen** [comment]
@Mackiovello awesome!

**Comment by Mackiovello** [comment]
It seems like everything has been set up for GitHub pages to work with Jekyll. Do you know why that wasn't finished?

**Comment by dennisdoomen** [comment]
Finished?

**Comment by Mackiovello** [comment]
This project wasn't published with GitHub Pages even if it was prepared in https://github.com/dennisdoomen/CSharpGuidelines/commit/7dfde146656845db70ee072dc3cdd7b8a5df759a

**Comment by dennisdoomen** [comment]
Ah, I had to switch the source of the pages to the _master_ branch. Now it works.

**Comment by dennisdoomen** [comment]
It's alive!

**Comment by dennisdoomen** [comment]
Done.
