### ISSUE TITLE
Cheatsheet style is broken in preview of Cheatsheet.md

### ISSUE THREAD

**Issue by vendettamit** [dennisdoomen/CSharpGuidelines#25]
Mark down is broken in CheatSheet.md. Preview is showing cluttered information. Issue might be because Github MD editor is upgraded in new Github repo preview. 

https://github.com/dennisdoomen/csharpguidelines/blob/master/Cheatsheet/Cheatsheet.md

**Comment by dennisdoomen** [comment]
Hmm. You're right. No clue why it is broken.

**Comment by dennisdoomen** [comment]
No wait, it probably never worked correctly since that file is relying on Markdown Extra for layout purpose.

**Comment by vendettamit** [comment]
How about creating a new branch/version that would be git hub editor friendly? Later it can be launched as Github Wiki pages and MD extra version would remain as-is.

**Comment by dennisdoomen** [comment]
Hmm. Sounds like a decent idea, although I would prefer to keep a single source of truth, which can be used both online *and* serve as the source for the PDF.

**Comment by dennisdoomen** [comment]
Decided to drop this issue. I'm now using Pandoc to generate the HTML version and Github doesn't support tables.
