### ISSUE TITLE
Overly restrictive license restricts usage

### ISSUE THREAD

**Issue by cocowalla** [dennisdoomen/CSharpGuidelines#27]
I had hoped to adapting these guidelines for internal use in the company I work for, while of course giving proper attribution to you.

However, the CC license chosen, 'Attribution-NonCommercial-NoDerivatives' (CC BY-NC-ND), is the most restrictive CC license available, and 'human readable' interpretations seem to agree that the license does not allow any modifications, rendering my use case in breach of license terms.

1. [Creative Commons](https://creativecommons.org/examples/#by-nc-nd)
2. [Wikimedia](https://meta.wikimedia.org/wiki/Open_Content_-_A_Practical_Guide_to_Using_Creative_Commons_Licences/The_Creative_Commons_licencing_scheme)
3. [Sara F. Hawkins](http://sarafhawkins.com/creative-commons-licenses-explained-plain-english/)

I would have thought that my use case, adapting for internal use, would have been the main aim of publishing this work (which is great, BTW!), so the choice of license is puzzling. Was it your intention to restrict its use (your prerogative if so), or did you have permitting wider usage in mind?

**Comment by dennisdoomen** [comment]
You can probably blame me for insufficient knowledge of licenses. Any suggestions?

**Comment by cocowalla** [comment]
:)

If you want to stay with a CC license, the [CC Attribution](https://creativecommons.org/examples/#by-nc-nd) (CC BY) license seems very permissive.

The [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0) license is very popular, and I tend to use it myself. It also includes text related to granting of patent rights, which makes it more favourable from a copyleft perspective. [Summary](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29).

**Comment by cocowalla** [comment]
@dennisdoomen what are your thoughts on this?

**Comment by dennisdoomen** [comment]
What I would like is allowing companies to modify it for internal use only.

**Comment by cocowalla** [comment]
Most licenses don't forbid commercial use, because it is such a broad term that could encompass almost anything. It seems that even Creative Common, despite having such clauses in some of their licenses, will not attempt to define what is classed as commercial use [say](https://creativecommons.org/faq/#Does_my_use_violate_the_NonCommercial_clause_of_the_licenses.3F) _"CC cannot advise you on what is and is not commercial use"_. More [here](https://wiki.creativecommons.org/wiki/NonCommercial_interpretation).

For this reason, I doubt many companies would feel comfortable using any non-commercial licensed content internally.  From what you've said. I think using a CC NC license is going to prevent basic uses of your work that you'd actually like to allow.

I think it's rather unlikely that a corporation would attempt to profit from this work. However, if you really want to attempt to restrict this, maybe the popular [LGPL] (https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-%28lgpl-3%29) or less popular CC [BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) license could work for you. These technically allows commercial use, but any distribution of adapted works must also be LGPL or CC-BY-SA licensed (e.g. freely available).

**Comment by cocowalla** [comment]
Hi, was wondering if you'd had a chance to look at different licensing possibilities yet?

I'd love to be able to adopt these guidelines internally, and hopefully contribute back too.

**Comment by dennisdoomen** [comment]
So, I want to stimulate organizations to copy and adapt the guidelines for internal use, but prevent them from commercially publishing their own guidelines.

**Comment by AndersAbel** [comment]
I think that what you want is CC-BY-SA. BY=Attribution required, so anyone publishing (original or adapted versions) must link back to your original. SA = Share Alike, so a commercial organization may publish (original or adapted version) but must do that under the CC-BY-SA license.

 I use CC-BY-SA for all of my blog posts to encourage reuse but to prevent commercial companies from selling the texts as there own.

**Comment by cocowalla** [comment]
Yes, CC-BY-SA would be permissive enough to allow companies to adopt these guidelines but not profit from them.

**Comment by dennisdoomen** [comment]
OK. CC-BY-SA is it going to be. Now I need to find some time to copy and nicely format the contents of http://creativecommons.org/licenses/by-sa/3.0/legalcode into the license.md.

**Comment by cocowalla** [comment]
How about I save you some work and send you a pull request instead? :)

**Comment by dennisdoomen** [comment]
Exactly what I was hoping for ;-)

**Comment by cocowalla** [comment]
Resolved by #29 - thanks for being so receptive to change
