### ISSUE TITLE
Should records be added as an exception to AV1561 (max 3 parameters in signature)?

### ISSUE THREAD

**Issue by weelink** [dennisdoomen/CSharpGuidelines#270]
We are using C# records for modelling our events. Because all the events have at least the aggregate id, this rule limits the amount of extra information to 2, which is not very practical, e.g:

```csharp
public sealed record UserImportedEvent(
    Guid Id,
    string ExternalId,
    string Name,
    string EmailAddress
) : IEvent;
```

Currently we use `#pragma warning disable AV1561`, but I think this should be an exception.

**Comment by bkoelman** [comment]
@weelink it looks like you're in the wrong repository. Please create your issue at https://github.com/bkoelman/CSharpGuidelinesAnalyzer instead.

**Comment by weelink** [comment]
I wasn't too sure about where to put this. The `#pragma` is the analyzer, but the principle is the convention. But I'll add this to the other repository. Thanks.
