### ISSUE TITLE
AV2400: Add exception for simple properties?

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#273]
Rule "Use a common layout (AV2400)" states:
> Always put opening and closing curly braces on a new line.

I'm wondering if an exception should be added for simple properties/events, which would require to use:
```c#
public string Value { get; set; } = "default";
```

instead of:
```c#
public string Value
{
    get; set;
}
= "default";
```

Thoughts?

**Comment by dennisdoomen** [comment]
I absolutely agree with that.
