### ISSUE TITLE
Error AV1500 caps max class statements instead of methods when using primary constructors

### ISSUE THREAD

**Issue by TomasMalcanek** [dennisdoomen/CSharpGuidelines#275]
**Description:**
When a primary constructor is used, and inheriting another class the AV1500 is counting statements in the class instead of single methods.

**Code to test:**
```csharp
public class Skoda(string someParameter) : Car(someParameter)
{
    void Method1()
    {
        int statement = 1;
        statement += 1;
        statement += 1;
        statement += 1;
        statement += 1;
    }

    void Method2()
    {
        int statement = 1;
        statement += 1;
        statement += 1;
        statement += 1;
        statement += 1;
        statement += 1;
    }

    void Method3()
    {
        int statement = 1;
        statement += 1;
        statement += 1;
        statement += 1;
    }
}

public class Car(string someParameter)
{
    public string SomeParameterUpper => someParameter.ToUpper();
}
```

![image](https://github.com/dennisdoomen/CSharpGuidelines/assets/111517390/156d9395-5a6a-48f7-a9af-b4ee4a8b7bbe)

**Versions:**
Using .NET 8

**Comment by bkoelman** [comment]
This should be fixed in the latest version. Which version are you using?

**Comment by TomasMalcanek** [comment]
Well, that would be the fastest fix.
I did have the 3.8.4 version, I just checked github changelogs and not my nuget version :D
Updated to 3.8.5 and it's gone.
