### ISSUE TITLE
Project conatins incompatible licenses 

### ISSUE THREAD

**Issue by cduhard** [dennisdoomen/CSharpGuidelines#31]
The licensing referenced in **_LICENSE.md_** does not match the license referenced in _**0001_Introduction.md**_

License.md -> _

> Creative Commons Attribution-ShareAlike 4.0 International Public License

_

0001_Introduction.md ->

>  _This document is published under a Creative Commons license, specifically the Attribution-NonCommercial-NoDerivatives-4.0 license._

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Fixed it immediatelly.
