### ISSUE TITLE
AV1535 What benefits of braces after case?

### ISSUE THREAD

**Issue by s-tarasov** [dennisdoomen/CSharpGuidelines#32]
> Always add a block after keywords such as if, else, while, for, foreach and case (AV1535)

**Comment by dennisdoomen** [comment]
Readability is the most important reason.

**Comment by s-tarasov** [comment]
Readability is matter of habit.
Оther c# guidlines do not have this rule.

A switch-case does not create its own declaration space.
So, rule change operator scope.
https://ericlippert.com/2009/08/13/four-switch-oddities/

**Comment by dennisdoomen** [comment]
It's a matter of taste here. That's why I allow (and stimulate) people to fork my repo for internal use.

**Comment by s-tarasov** [comment]
Of course) We have fork. Understanding rules is important too.
Thank you for the quick response and brilliant guideline.
