### ISSUE TITLE
AV1570: When to use the "is" operator?

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#40]
# AV1570: Always check the result of an as operation
> If you use `as` to obtain a certain interface reference from an object, always ensure that this operation does not return `null`. Failure to do so may cause a `NullReferenceException` at a much later stage if the object did not implement that interface. **If you are sure the object is of a certain type, use the `is` operator instead.**

The last sentence is not clear to me. If I know the target type upfront, I would use an explicit conversion (cast). The `is` operator today seems only useful for type checks when the derived members are not used.

Should the sentence maybe be: "If you are **not** sure..."?

**Comment by dennisdoomen** [comment]
Yeah, I think we should remove that last statement. I remember that I introduced this guideline after seeing somebody use it in a real weird way, but I can't recall the exact example.
