### ISSUE TITLE
Acronym naming

### ISSUE THREAD

**Issue by AlexArchive** [dennisdoomen/CSharpGuidelines#5]
Here is the standard convention that I have observed for acronyms: 
- If the acronym is precisely two characters in length, use upper casing (`UI` `IO`)
- If the acronym is more than two characters in length, use Pascal casing (`Http` `Sql`)

I _think_ this convention is consistent for public types and members throughout the foundation class library.

I noticed that developers tend to stray from this convention when it comes to variables called `Id` though. 

I would be interested to hear your thoughts.

**Comment by dennisdoomen** [comment]
Yes, I agree. [AV1706](https://github.com/dennisdoomen/csharpguidelines/blob/master/Guidelines/1700_NamingGuidelines.md#dont-use-abbreviations--av1706-) used to include this rule. Will update this. 

PS. Apparently I wasn't getting any email notifications, so I just noticed your issue right now.

**Comment by dg9ngf** [comment]
I'd put this into AV1702 instead which is about casing.

**Comment by lorddev** [comment]
Don't forget to mention the "Id" rule. Since ID is not an acronym, but an abbr. for identity, it doesn't fit the Acronym rule. https://msdn.microsoft.com/en-us/library/vstudio/ms229043%28v=vs.100%29.aspx

**Comment by bkoelman** [comment]
I think this can be closed now.
