### ISSUE TITLE
Feature request: add anchors to rules

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#52]
This would enable users to click on the Rule ID in the Error List on rule violations that are reported by [CSharpGuidelinesAnalyzer](https://github.com/bkoelman/CSharpGuidelinesAnalyzer). Once a user clicks on the link, VS opens a browser window, similar to built-in FxCop rules.

![image](https://cloud.githubusercontent.com/assets/10324372/19495362/59cf8686-9583-11e6-9ac5-e58e1a51ea58.png)

Currently all rules within a category link to the same URL.

**Comment by dennisdoomen** [comment]
GitHub already does that by default. See https://github.com/dennisdoomen/CSharpGuidelines/blob/master/Src/Guidelines/1000_ClassDesignGuidelines.md#use-an-interface-rather-than-a-base-class-to-support-multiple-implementations-av1004-

**Comment by bkoelman** [comment]
Nice, I did not know that.

However, as titles may change over time, I'd prefer to have a stable identifier to link to.

I've tried the following, which works nicely, both in build output and source .md files on GitHub:

```
### <a name="av1013"></a> Don't refer to derived classes from the base class (AV1013) ![](images/1.png)
```

This enables links like:
https://github.com/bkoelman/CSharpGuidelines/blob/anchors/Src/Guidelines/1000_ClassDesignGuidelines.md#av1013

I'd be happy to submit a PR in which all rules are updated like above.

**Comment by dennisdoomen** [comment]
Sure. If you can't restrain yourself ;-)

**Comment by bkoelman** [comment]
No problem, piece of cake!

```csharp
class Program
    {
        private static readonly Regex RuleHeaderRegex =
            new Regex(@"^###\s*(?<Title>.*)\((?<RuleID>AV[0-9]{4})\)(?<Suffix>.*)$", 
            RegexOptions.Compiled);

        static void Main()
        {
            foreach (string path in Directory.GetFiles(
                @"E:\Bart\Source\Repos\CSharpGuidelines\Src\Guidelines", "*.md"))
            {
                var linesInFile = new List<string>();

                foreach (string line in File.ReadAllLines(path))
                {
                    Match match = RuleHeaderRegex.Match(line);
                    if (match.Success)
                    {
                        string title = match.Groups["Title"].Value;
                        string ruleId = match.Groups["RuleID"].Value;
                        string suffix = match.Groups["Suffix"].Value;

                        string lineWithAnchor = 
                            $"### <a name=\"{ruleId.ToLowerInvariant()}\"></a> {title}({ruleId}){suffix}";
                        linesInFile.Add(lineWithAnchor);
                    }
                    else
                    {
                        linesInFile.Add(line);
                    }
                }

                File.WriteAllLines(path, linesInFile);
            }
        }
    }
```
