### ISSUE TITLE
AV1010 Don't hide inherited members with the new keyword - Wrong new does not hide anything more than the warning compiler

### ISSUE THREAD

**Issue by MarcoMedrano** [dennisdoomen/CSharpGuidelines#6]
It is easy to check just remove the 'new' keyword and you will get same result as when using it, that means that 'new' keyword does not affect at all the execution behaviour. It is intended just to make explicit your decision of hide a base class behaviour, so the compiler does not warn you any more. Usually that wont be a good implementation but C# gives you the power to decide rather than other languages like Java where members are always virtual, so we need to use it wisely; but saying that 'new' keyword hides inherited members is wrong, with 'new' or without it inherited members are hidden, the unique way to keep polymorphism is by using the 'override' keyword.

With 'new'

```
public class PocketBook : Book  
{
    public new void Print()
    {
        Console.WriteLine("Printing PocketBook");
    }  
}
```

Without 'new'

```
public class PocketBook : Book  
{
    public void Print()
    {
        Console.WriteLine("Printing PocketBook");
    }  
}
```

Then

```
PocketBook pocketBook = new PocketBook();
((Book)pocketBook).Print(); // Will output "Printing Book"
```

Both have same result:

```
"Printing Book"
"Printing Book"
```

**Comment by dennisdoomen** [comment]
Hmm, I need to check that.

**Comment by bkoelman** [comment]
I verified, @MarcoMedrano is correct. I think the rule should be rephrased a bit (while preserving its original intention). I'll give it a try, PR coming.
