### ISSUE TITLE
AV1520 not supported by provided reference

### ISSUE THREAD

**Issue by cbrhea** [dennisdoomen/CSharpGuidelines#60]
It seems the standard for AV1520 is far more strict than necessary and isn't supported by Eric Lippert's article that's used as a reference.

It's very rare that someone needs to know what type is used for a declaration as simple as your first "don't" example:
`var i = 3;`

In Eric Lippert's article, he summarizes:
- Consider using var if the code emphasizes the semantic “business purpose” of the variable and downplays the “mechanical” details of its storage.
- Use explicit types if doing so is necessary for the code to be correctly understood and maintained.

**Comment by dennisdoomen** [comment]
It's a recurring debate. I've settled on avoiding *var* for built-in types (for now).
