### ISSUE TITLE
Update rules for .NET core

### ISSUE THREAD

**Issue by anandtpatel** [dennisdoomen/CSharpGuidelines#61]

**Comment by dennisdoomen** [comment]
What kind of update are you suggesting?

**Comment by bkoelman** [comment]
@anandtpatel Is [this](https://github.com/dennisdoomen/CSharpGuidelines/issues/83) what you had in mind?

**Comment by dennisdoomen** [comment]
Since there was no response from @anandtpatel, I'm closing this issue.
