### ISSUE TITLE
Suggestion: Add rule for expression-bodied members

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#69]
[Expression-bodied members](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members) were introduced in C# 6 and extended in C# 7.

Example (C# 6):
```csharp
public void DisplayName() => Console.WriteLine(ToString());
```

Example (C# 7):
```csharp
public string Name
{
    get => innerName;
    set => innerName = value;
}
```

The new rule could be something like: Only allow expression syntax on properties and indexers.

Is this worth mentioning / any strong feelings on this?

**Comment by bkoelman** [comment]
I propose the following guidance: 

Favor an expression bodied member over a regular member only when:
- the body consists of a single statement and
- the body fits on a single line.

Can be added to the Layout section as a separate rule, or include in [AV2400](https://github.com/dennisdoomen/CSharpGuidelines/blob/master/_pages/2400_LayoutGuidelines.md).

**Comment by dennisdoomen** [comment]
I think this should be a separate rule.
