### ISSUE TITLE
Suggestion: Consider to use var more broadly (AV1520)

### ISSUE THREAD

**Issue by SergeyRusskih** [dennisdoomen/CSharpGuidelines#74]
According to the Eric Lippert's article, explicit types are used only when it's necessary:
> Use explicit types if doing so is necessary for the code to be correctly understood and maintained.

I also got lots of complaints about using explicit types from the readers of the Russian translation. Visual Studio and ReSharper allow getting the information about the variable's type by just mouse covering. Whereas, `var` increases readability. 

Could we consider this?

**Comment by dennisdoomen** [comment]
I've reconsidered it many times, but I still strongly object against it. I've ran into too many errors because people made the wrong assumptions in pull request reviews (where you can't hover).

**Comment by cbrhea** [comment]
> I've ran into too many errors because people made the wrong assumptions in pull request reviews

Dennis, doesn't that just mean that `var` was used in violation of Lippert's suggestion?

It doesn't feel like the right answer is a blanket statement against the `var` keyword.

**Comment by dennisdoomen** [comment]
> Dennis, doesn't that just mean that var was used in violation of Lippert's suggestion?

My point is that that's almost always the case.  If a statement doesn't explicitly mention the type somewhere, I still believe you should not use `var`. Even for primitives, I've seen people not realizing they should use `long` instead of an `int` and running into overflow exceptions.

**Comment by cbrhea** [comment]
I still feel you and Lippert are saying the same thing, unless you're 100% against var in all cases.

I have begun reducing my use of `var` considerably after reading this guide and participating in some oddly formatted code reviews.

**Comment by dennisdoomen** [comment]
> Use explicit types if doing so is necessary for the code to be correctly understood and maintained.

@cbrhea If this is what he said, we do agree. But I've reversed the emphasis by saying that you should use explicit types, unless the type is already very explicit. In that case, `var` is fine.
