### ISSUE TITLE
AV1545: Add example for ternary operator

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#86]
In my opinion, this rule also applies to the ternary operator (?:).

Besides that, the existing examples have some shortcomings:
* The abbreviated names `pos` and `val` used in the examples violate AV1706 (Don't use abbreviations)
* The string null check doesn't play nicely with AV1135 (Properties, methods and arguments representing strings or collections should never be null)
* The comment `// initialization` should be removed (or added to both before/after examples)

**Comment by dennisdoomen** [comment]
You have a sharp eye 😉

**Comment by bkoelman** [comment]
Thanks. It's not entirely me, though. The ternary came from a colleague. The nitpicking is me :)

 Proposed new examples:

1:
```csharp
	bool isPositive;

	if (value > 0)
	{
		isPositive = true;
	}
	else
	{
		isPositive = false;
	}
```

```csharp
	isPositive = (value > 0);
```

2.
```csharp
	string classification;

	if (value > 0)
	{
		classification = "positive";
	}
	else
	{
		classification = "negative";
	}

	return classification;
```

```csharp
	return (value > 0) ? "positive" : "negative";
```

3:
```csharp
	int result;

	if (offset == null)
	{
		result = -1;
	}
	else
	{
		result = offset.Value;
	}

	return result;
```

```csharp
	return offset ?? -1;
```
