### ISSUE TITLE
AV1506: Add guidance for generic types

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#87]
Applies to: "Name a source file to the type it contains (AV1506)"

Consider the next file:

```csharp
public class TableLoader
{
    // ...
}

public class TableLoader<TKey, TConverter> : TableLoader
{
    // ...
}
```

Options:
1. Allow both types to live in the same file, because their names are the same (they only differ in arity)
2. Split into TableLoader.cs and TableLoader`2.cs (because arity = 2)
3. Split into TableLoader.cs and TableLoaderTKeyTConverter.cs
4. Split into TableLoader.cs and TableLoader.generic.cs (nested)

I think it is worth providing guidance on this situation, to align naming accross the entire team. My preference would be 2. Though I often see option 1 in codebases too.

**Comment by dennisdoomen** [comment]
I usually keep them together, so my preference is option 1.

**Comment by bkoelman** [comment]
The same for nested types, right?

An alternative would be to put them in partial classes and in separate files, but I'm not a big fan of that.

**Comment by dennisdoomen** [comment]
Neither am I.
