### ISSUE TITLE
method name in

### ISSUE THREAD

**Issue by OlegKleyman** [dennisdoomen/csharpguidelines#9]
File 1100_MemberDesignGuidelines.md contains what looks like a typo. It says

"Returning null can be unexpected by the caller. Always return an empty collection or an empty string instead of a null reference. This also prevents cluttering your code base with additional checks for null, or even worse, string.IsNotNullOrEmpty()."

Notice the string.IsNotNullOrEmpty(). The method is actually called "IsNullOrEmpty"

**Comment by dennisdoomen** [comment]
Very perceptive... thanks!
