### ISSUE TITLE
AV1521: Scope & declaration space for out var, patterns and local functions

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#96]
### Existing rule:

**`Declare and initialize variables as late as possible (AV1521)`**
`Avoid the C and Visual Basic styles where all variables have to be defined at the beginning of a block, but rather define and initialize each variable at the point where it is needed.`

### New language features to consider:
- Out variables
Variables can be declared in the middle of a statement, such as a method call. For example: 
```csharp
if (int.TryParse(text, out int result) && result > 0)
{
}
```
- Pattern matching
Variables can be declared in the `case` clauses of a `switch` statement. For example:
```csharp
public static double ComputeArea(object shape)
{
    switch (shape)
    {
        case Square s:
            return s.Side * s.Side;
        case Circle c:
            return c.Radius * c.Radius * Math.PI;
        case Rectangle r:
            return r.Height * r.Length;
        default:
            throw new ArgumentException(
                message: "shape is not a recognized shape",
                paramName: nameof(shape));
    }
}
```
- Local functions
Can be declared at top, right-before usage and even *after* being used. They are not variables though, so this rule does not apply to them in the current form. Example:
```csharp
public void M()
{
    L();

    void L()
    {
        Console.WriteLine("Hello");
    }
}
```

**Comment by dennisdoomen** [comment]
I like the new `out` parameter option. I've already used it a couple of times. 

I have not found any good examples of using a local function, although they seem to be faster than lambdas.

I definitely don't like the pattern matching technique. They seem convenient, but I'm pretty sure they will lead you a path of often violations of the Open Closed Principle.

**Comment by bkoelman** [comment]
Local functions are slightly more optimal over delegate instances, because they do not need heap allocations. But that's more of a theoretical issue for most business-line applications. Aside from expressing reduced accessibility, they can be used to simplify non-deferred argument validation in async and iterator methods (see example in https://github.com/dennisdoomen/CSharpGuidelines/issues/92).

I get your point about violating the Open-Closed Principle.

Concerning AV1521: unless you want to forbid usage of pattern matching constructs, I don't think this rule needs any changes for these new language features.

**Comment by bkoelman** [comment]
Closing, as the discussion seems to have been abandoned. No feedback received in the last two weeks. Feel free to reopen if needed.
