### ISSUE TITLE
AV1522: Multiple assignments per statement using out var, patterns and tuples

### ISSUE THREAD

**Issue by bkoelman** [dennisdoomen/CSharpGuidelines#97]
### Existing rule:

**`Assign each variable in a separate statement (AV1522)`**
`Don't use confusing constructs like the one below:`
`var result = someField = GetSomeMethod();`

### New language features to consider:
- out variables
Variables can be declared in the middle of a statement, such as a method call. The next example violates this rule in its current form: 
```csharp
bool success = int.TryParse(text, out int result);
```
- Pattern matching
Variables can be declared in an is-pattern. The next example violates this rule in its current form: 
```csharp
if (items[0] is string text || items[1] is Action action)
{
}
```
- Tuples
A tuple can be deconstructed into multiple variables. The next example violates this rule in its current form: 
```csharp
(int a, int b) = M();
```

**Comment by dennisdoomen** [comment]
I agree with all proposals. I do prefer to write the second example as:

```csharp
if ((items[0] is string text) || (items[1] is Action action))
{
}
```
